store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.search, name='search'),
    path('search/suggestions/', views.search, name='search-suggestions'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:subcategory_slug>/', views.subcategory_detail, name='subcategory_detail'),
    path('<str:category_slug>/<str:subcategory_slug>/<str:slug>/', views.product_detail, name='product_detail'),

]
#path('cart/success/', views.success, name='success'),
'''path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('change-quantity/<str:product_id>/', views.change_quantity, name='change_quantity'),
    path('remove-from-cart/<str:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/checkout/', views.checkout, name='checkout'),'''
#path('category/<str:category_slug>/<str:slug>/', views.product_detail, name='product_detail_no_subcategory'),

userprofile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    path('privacy/', views.privacy, name='privacy'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginView ,name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='userprofile/password_change_form.html'), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='userprofile/password_change_done.html'), name='password_change_done'),
    

    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userprofile/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userprofile/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userprofile/password_reset_complete.html'), name='password_reset_complete'),

    path('myaccount/', views.myaccount, name='myaccount'),
    path('edit-account/', views.edit_account, name='edit_account'),
    path('my-store/', views.my_store, name='my_store'), 
    path('create-subscription/', views.create_subscription, name='create_subscription'),
    path('update_vendor_status/', views.update_vendor_status, name='update_vendor_status'),

    path('my-store/add-product/',views.add_product, name='add_product'),
    path('my-store/edit-product/<int:pk>/', views.edit_product, name='edit_product'),

    path('get-subcategories/', views.get_subcategories, name='get_subcategories'),
    
    path('my-store/delete-product/<int:pk>/',views.delete_product, name='delete_product'),
    path('vendors/<int:pk>/', views.vendor_detail, name='vendor_detail'),
]

#path('my-store/order-detail/<int:pk>/', views.my_store_order_detail, name='my_store_order_detail'),

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from PIL import Image
from io import BytesIO
from django.utils.text import slugify
from random import randint
from django.contrib.humanize.templatetags.humanize import intcomma
from django.db import models



class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self): 
        return self.title
    class Meta:
        verbose_name_plural='Category/Industry'
        ordering = ('title',)



class Subcategory(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Subcategories'
        ordering = ('category',)



class Product(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'

    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )
    
    user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, related_name='products', on_delete=models.CASCADE , null=True, blank=True)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    userprofile = models.ForeignKey('userprofile.Userprofile', related_name='products', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(blank=True)
    brand = models.CharField(max_length=20 , blank=True, null=True)
    model = models.CharField(max_length=20 , blank=True, null=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='uploads/product_images', null=True)
    image_2 = models.ImageField(upload_to='uploads/product_images', blank=True, null=True)
    image_3 = models.ImageField(upload_to='uploads/product_images', blank=True, null=True)
    image_4 = models.ImageField(upload_to='uploads/product_images', blank=True, null=True)
    condition = models.CharField(max_length=50, null=True, blank=True ,choices=(
        ('New','New'),
        ('Used', 'Used')
    ))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self): 
        return self.title

    

    def formatted_price(self):
        return intcomma(self.price)

    # a method used to create a unique slug
    def save(self, *args, **kwargs):
        if Product.objects.filter(title=self.title).exists():
            extra = str(randint(1, 1000000))
            self.slug = slugify(self.title) + "-" + extra
        else:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)


    #to automatically generate a thumbnail based on the image 







'''class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    email = models.EmailField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.IntegerField()
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255, blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.first_name
    
    


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)'''

    



    

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models import Q






class State(models.Model):
    state = models.CharField(max_length=20, null=True,blank=True)

    class Meta:
        ordering = ['state']
    
    def __str__(self): 
        return self.state
     
     
class Userprofile(models.Model):
    company_image = models.ImageField(null=True, blank=True, upload_to='uploads/profile_pic')
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    company_whatsapp_number = PhoneNumberField(null=True, blank=True, verbose_name='WhatsApp')
    company_address = models.CharField(max_length=255, blank=True, null=True, verbose_name='Address')
    website = models.CharField(max_length=225, null=True, blank=True)
    about = models.TextField(blank=True, null=True)
    state = models.ForeignKey(State, max_length=20, null=True, blank=True, on_delete=models.CASCADE)
    lga = models.CharField(max_length=20, null=True, blank=True)
    is_vendor = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username
      
vendors = Userprofile.objects.filter(is_vendor=True)
non_vendors = Userprofile.objects.filter(~Q(is_vendor=True))







  

userprofile/templates/userprofile/create_subscription.html
{% extends 'core/base.html' %}
{% block title %}Create Subscription{% endblock %}
{% block content %}
<div class="bg-gray-100 py-10">
  <div class="max-w-3xl mx-auto px-4">
    <h1 class="text-3xl md:text-4xl font-bold text-gray-800 text-center mb-6">Why Should You Subscribe to AutoAngol?</h1>
    <p class="text-lg text-gray-700 mb-4">By subscribing, you will have full access to your store. With AutoAngol, you can:</p>
    <ul class="list-disc list-inside text-gray-700 mb-8">
      <li>Add your products to your online store and reach a wider audience.</li>
      <li>Sell your products to customers online, increasing your sales and revenue.</li>
      <li>Edit your products anytime to keep your store up to date and offer new items.</li>
      <li>Enable customers to view your profile and establish trust.</li>
      <li>Showcase a variety of products available in your store, attracting more customers.</li>
      <li>Promote your products on the homepage, gaining maximum visibility.</li>
    </ul>
  </div>

  <div class="bg-gray-100 flex items-center justify-center py-10">
    <div class="bg-white max-w-md w-full rounded-lg shadow-md p-6">
      <h1 class="text-3xl md:text-4xl font-bold text-gray-800 text-center mb-6">Create Subscription</h1>
      <form action="{% url 'create_subscription' %}" method="post">
        {% csrf_token %}

        <div class="mb-6">
          <p class="text-lg text-gray-800">Select a Plan:</p>
          <div class="flex items-center mt-2">
            <input type="radio" name="plan" id="plan" value="9000" required class="mr-2">
            <label for="plan" class="text-gray-700">Plan - Kz9,000 for 1 month</label>
          </div>
        </div>

        <div class="flex justify-center">
          <button type="submit" class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded">
            Subscribe Now and Grow Your Online Business!
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

userprofile/templates/userprofile/edit_account.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block title %}Edit Account{% endblock %}
{% block content %}
    <div class="max-w-7xl mx-auto my-auto min-h-screen">
        <h1 class="mb-5 text-3xl">{% trans "Edit Account" %}</h1>
        <div>
        <form method="post" enctype="multipart/form-data" class="space-y-6">
            {% csrf_token %}

            {% if form.errors %}
                <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
                    <strong class="font-bold">{% trans "Form submission failed!" %}</strong>
                    <ul class="mt-1 mb-0 list-disc">
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li>{{ field.label }}: {{ error }}</li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div>
                <label for="id_company_image">{% trans "Company Image" %}</label>
                <input type="file" name="company_image" id="id_company_image">
            </div>

            <div>
                <label for="id_user">{% trans "Company Name" %}</label>
                <label for="id_user">( {% trans "To Change this" %}, <a href="mailto:theautoangol@outlook.com" class="no-underline">{% trans "contact us" %}</a>)</label>
                <input type="text" value="{{ user.username }}" readonly class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
            </div>
            
            <div>
                <label for="id_company_whatsapp_number">{% trans "WhatsApp Number" %}</label>
                {{ form.company_whatsapp_number }}
            </div>

            <div>
                <label for="id_website">{% trans "Company Website(Optional)" %}</label>
                {{ form.website }}
            </div>

            <div>
                <label for="id_state">{% trans "State" %}</label>
                {{ form.state }}
            </div>

            <div>
                <label for="id_lga">{% trans "LGA" %}</label>
                {{ form.lga }}
            </div>

            <div>
                <label for="id_company_address">{% trans "Company Address" %}</label>
                {{ form.company_address }}
            </div>

            <div>
                <label for="id_about">{% trans "About" %}</label>
                {{ form.about }}
            </div>

            <div>
                <button type="submit" class="py-4 px-6 rounded-xl text-white bg-purple-500">{% trans "Save" %}</button>
            </div>
        </form>
        <div><a class="dropdown-item" href="{% url 'password_change'%}">{% trans "Change password" %}</a></div>
        </div>
    </div>
{% endblock %}

userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block title %}Login{% endblock %}
{% block meta %}
<meta name="description" content="Autoangol login page">
{% endblock %}
{% block content %}
<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-200 p-6 rounded-xl">
        <h1 class="mb-6 text-2xl">{% trans "Log in" %}</h1>

        <form method="post" action="." class="space-y-3">
            {% csrf_token %}
            <div>
                <label>{% trans "Username" %}</label>
                <input type="text" name="username" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            <div>
                <label>{% trans "Password" %}</label>
                <input type="password" name="password" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{ error|escape }}</p>
                        </div>
                    {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                    <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                        <p>{{ error|escape }}</p>
                    </div>
                {% endfor %}
            {% endif %}

            <div>
                <button class="py-4 px-6 rounded-xl text-white bg-teal-500 hover:bg-teal-800">{% trans "Login" %}</button>
            </div>
        </form>
        <p>{% trans "Don't have an account with us?" %} <a href="{% url 'signup' %}" class="no-underline text-blue-500"> {% trans "Sign Up" %}</a></p>
        <p><a href="{% url 'password_reset' %}">{% trans "Forgotten your password?" %}</a></p>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/my_store.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block title %}My Store{% endblock %}

{% if messages %}
{% for message in messages %}
    <div class="mt-4 px-8 py-4 bg-teal-200 text-teal-800 rounded-md">{{message}}</div>
{% endfor %}
{% endif %}

{% block content %}  
    <h1 class = "text-2xl font-serif">{% trans "My Store" %}</h1>
    {{ user.username }}
 

<!--{% comment %}
    <h2 class="mt-6 text-xl">My orders</h2>
    
    <div class="flex flex-wrap">
        <div class="w-1/4">
            <strong>Order ID</strong>
        </div>

        <div class="w-1/4">
            <strong>Title</strong>
        </div>

        <div class="w-1/4">
                <strong>Quantity</strong>
        </div>

        <div class="w-1/4">
            <strong>Price</strong>
        </div>
    </div>
    {%  for order_item in order_items  %}
        <div class="flex flex-wrap">
            <div class="w-1/4">
               <a href="{% url 'my_store_order_detail' order_item.order.id %}">{{order_item.order.id}}</a>
            </div>
            <div class="w-1/4">
                {{order_item.product.title}}
            </div>

            <div class="w-1/4">
                {{order_item.quantity}}
            </div>

            <div class="w-1/4">
                ₦{{order_item.price}}
            </div>
        </div>
        
    {% endfor %}
    <hr>
    {% endcomment %}
-->

    <!--MY products-->
    <hr class="border-t-2 border-gray-300 my-8">

    <a href="{% url 'add_product' %}" class="mt-6 py-4 px-8 bg-teal-500 text-white no-underline inline-block rounded-2xl">{% trans "Add Product" %}</a>
    <h2 class="mt-6 text-xl font-serif">{% trans "My Products" %}</h2>
    
        {% if products %}
        <div class="bg-gray-100">
        <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
        <div class="grid grid-cols-2 gap-4 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
            {% for product in products %}
            <a href="{% url 'edit_product' product.pk %}" class="group no-underline shadow-sm">
                <div class="aspect-w-1 aspect-h-1 sm:aspect-w-1 sm:aspect-h-1 md:aspect-w-1 md:aspect-h-1 xl:aspect-w-1 xl:aspect-h-1">
                    <div class="w-30 h-40 sm:w-30 sm:h-40 overflow-hidden rounded-s-xl bg-gray-200">
                        <img src="{{ product.image.url }}" alt="Image of {{ product.title }}" class="object-cover object-center w-full h-full group-hover:opacity-75">
                    </div>
                </div> 
                
                <h3 class="mt-4 text-lg text-gray-700">{{ product.title }}</h3>
                <p class="mt-1 text-xs font-medium text-gray-900">₦{{ product.formatted_price }}</p>
                <p><strong class="text-gray-800">{% trans "Status" %}:</strong> {{ product.get_status_display }}</p>
            </a>
            {% endfor %}

            
        </div>
        <!-- Pagination links -->
      <div class="mt-8">
        {% if products.has_other_pages %}
          <nav class="flex items-center justify-center">
            <ul class="pagination">
              {% if products.has_previous %}
                <li>
                  <a href="?page=1" class="flex items-center justify-center w-8 h-8 bg-gray-200 text-gray-700 rounded-full hover:bg-gray-300 no-underline mr-1">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                    </svg>
                  </a>
                </li>
              {% endif %}
  
              {% for num in products.paginator.page_range %}
                {% if products.number == num %}
                  <li>
                    <a href="?page={{ num }}" class="flex items-center justify-center w-8 h-8 bg-teal-500 text-white rounded-full hover:bg-teal-600 no-underline mr-1">{{ num }}</a>
                  </li>
                {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
                  <li>
                    <a href="?page={{ num }}" class="flex items-center justify-center w-8 h-8 bg-gray-200 text-gray-700 rounded-full hover:bg-gray-300 no-underline mr-1">{{ num }}</a>
                  </li>
                {% endif %}
              {% endfor %}
  
              {% if products.has_next %}
                <li>
                  <a href="?page={{ products.paginator.num_pages }}" class="flex items-center justify-center w-8 h-8 bg-gray-200 text-gray-700 rounded-full hover:bg-gray-300 no-underline mr-1">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                  </a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}
        </div> 
        </div>
        <div><i class="fa fa-envelope  text-xl text-red-600"></i><a href="mailto:theautoangol.outlook.com" class="text-xl text-red-600 no-underline ml-2">{% trans "Contact us to Unsubscribe" %}</a></li></div>
        </div>
        {% else %}
                <p class="py-4 mt-4 px-8 bg-gray-200">{% trans "You don't have any product yet...." %}</p>
        {% endif %}

{% endblock %}

userprofile/templates/userprofile/my_store_order_detail.html
{% extends 'core/base.html' %}

{% block title %}
    order detail - {{order.id}}
{% endblock %}

{% block content %}
    <h1 class = "mb-6 text-2xl">Order detail - {{order.id}}</h1>

    <h2 class="mb-3 text-2xl">My Product in the order</h2>

    <div class="flex flex-wrap">
        

        <div class="w-1/3">
            <strong>Title</strong>
        </div>

        <div class="w-1/3">
                <strong>Quantity</strong>
        </div>

        <div class="w-1/3">
            <strong>Price</strong>
        </div>
    </div>

    {% for item in order.items.all %}
        {% if item.product.user == request.user %}
            <div class="flex flex-wrap">

                <div class="w-1/3">
                    {{ item.product.title }}
                </div>

                <div class="w-1/3">
                    {{ item.quantity }}
                </div>

                <div class="w-1/3">
                    ₦{{ item.price }}
                </div>

            </div>
        {% endif %}
    {% endfor %}

{% endblock %}

userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block title %}My Account{% endblock %}

{% block content %}
<body>
    <div class="container bg-gray-50 mx-auto p-4">
        <h1 class="text-2xl font-bold mb-4">{% trans "My Account" %}</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="md:col-span-1">
                {% if user.userprofile.company_image %}
                    <img src="{{ user.userprofile.company_image.url }}" alt="Company Image" class="mt-2 w-full rounded-full">
                {% else %}
                    <img src="/media/uploads/profile.png" alt="profile pic">
                {% endif %}
            </div>
            <div class="md:col-span-1">
                <p class="mt-2 text-2xl">{{ user.username }}</p>
            </div>

            <div class="md:col-span-1">
                <h2 class="text-lg font-semibold">{% trans "Email (contact us to change)" %}</h2>
                <p class="mt-2">{{ user.email }}</p>
            </div>
            <div class="md:col-span-1">
                <h2 class="text-lg font-semibold">WhatsApp</h2>
                <p class="mt-2">{{ user.userprofile.company_whatsapp_number }}</p>
            </div>
            {% if user.userprofile.website %}
            <div class="md:col-span-1">
                <h2 class="text-lg font-semibold">{% trans "Company Website" %}</h2>
                <a href="https://{{ user.userprofile.website }}"><p class="mt-2">{{ user.userprofile.website }}</p></a>
            </div>
            {% endif %}
            <div class="md:col-span-1">
                <h2 class="text-lg font-semibold">{% trans "State" %}</h2>
                <p class="mt-2">{{ user.userprofile.state }}</p>
            </div>
            <div class="md:col-span-1">
                <h2 class="text-lg font-semibold">{% trans "LGA" %}</h2>
                <p class="mt-2">{{ user.userprofile.lga }}</p>
            </div>
            <div class="md:col-span-1">
                <h2 class="text-lg font-semibold">{% trans "Address" %}</h2>
                <p class="mt-2">{{ user.userprofile.company_address }}</p>
            </div>
            {% if user.userprofile.about %}
            <div class="md:col-span-2">
                <h2 class="text-lg text-justify font-semibold">{% trans "About" %}</h2>
                <p class="mt-2">{{ user.userprofile.about }}</p>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="flex justify-between items-center mt-4">
        <a href="{% url 'edit_account' %}" class="inline-block py-4 px-6 rounded-xl text-white bg-purple-500 no-underline">{% trans "Edit" %}</a>
        <hr class="flex-grow md:hidden border-t border-gray-400">
        <a href="{% url 'logout' %}">
            <button class="py-4 px-6 rounded-xl text-white bg-red-500 hover:bg-red-700">{% trans "Logout" %}</button>
        </a>
    </div>
</body>
{% endblock %}

userprofile/templates/userprofile/product_form.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
{% if user.userprofile.is_vendor %}
    <h1 class="text-2xl">{{ title }}</h1> 

    <form id="product-form" action="." method="post" enctype="multipart/form-data" class="space-y-5">
        {% csrf_token %}

        <div>
            <label for="id_category">{% trans "Category" %}*:</label>
            {{ form.category }}
        </div>

        <div>
            <label for="id_subcategory">{% trans "Subcategory" %}*:</label>
            <select id="id_subcategory" class="w-full p-4 border border-gray-400" name="subcategory">
                
            </select>
        </div>

          <div class="mb-4">
            <label for="id_title" class="block">{% trans "Title" %}*:</label>
            {{ form.title }}
          </div>

          <div class="mb-4">
            <label for="id_brand" class="block">{% trans "Brand" %}:</label>
            {{ form.brand }}
          </div>
          
          <div class="mb-4">
            <label for="id_model" class="block">{% trans "Model(optional)" %}:</label>
            {{ form.model }}
          </div>

          <div class="mb-4">
            <label for="id_description" class="block">{% trans "Description" %}*:</label>
            {{ form.description }}
          </div>
        
          <div class="mb-4">
            <label for="id_price" class="block">{% trans "Price" %}*:</label>
            {{ form.price }}
          </div>
        
          <div class="mb-4">
            <label for="id_image" class="block">{% trans "Image" %}*:</label>
            {{ form.image }}
          </div>
          <div class="mb-4">
            <label for="id_image" class="block">{% trans "Image" %}:</label>
            {{ form.image_2 }}
          </div>
          <div class="mb-4">
            <label for="id_image" class="block">{% trans "Image" %}:</label>
            {{ form.image_3 }}
          </div>
          <div class="mb-4">
            <label for="id_image" class="block">{% trans "Image" %}:</label>
            {{ form.image_4 }}
          </div>
          <div>
            <label for="id_condition">{% trans "Condition (optional)" %}:</label>
            {{ form.condition }}
        </div>
        <button class="mt-4 py-4 px-6 rounded-xl bg-teal-500 text-white hover:bg-teal-800">{% trans "Upload" %}</button>
    </form>

    {% if product %}
        <a href="{% url 'delete_product' product.id %}" class="mt-4 no-underline inline-block  py-4 px-6 rounded-xl bg-red-500 text-white hover:bg-red-900">{% trans "Delete Product" %}</a>
    {% endif %}

    
<script>
   $(document).ready(function() {
    $('#id_category').change(function() {
        var categoryId = $(this).val();
        var subcategorySelect = $('#id_subcategory');

        // Clear existing subcategory options
        subcategorySelect.empty();

        // Only make the AJAX request if categoryId is a valid number
        if (!isNaN(categoryId)) {
            // Make AJAX request to fetch subcategories
            $.ajax({
                url: '/get-subcategories/',
                data: {
                    category_id: categoryId
                },
                success: function(data) {
                    // Populate subcategory options
                    $.each(data.subcategories, function(index, subcategory) {
                        subcategorySelect.append($('<option></option>').attr('value', subcategory.id).text(subcategory.title));
                    });
                },
                error: function(xhr, status, error) {
                    // Handle error
                    console.log(error);
                }
            });
        }
    });

    // Trigger change event on page load to fetch initial subcategory options
    $('#id_category').change();
});
</script>
{% else %}
<h1>{% trans "Please Subscribe" %}</h1>
<a href="{% url 'my_store' %}" class="no-underline"><i class="fa fa-arrow-left"></i> {% trans "My Store" %}</a>
{% endif %}

{% endblock %}